FROM 692490534637.dkr.ecr.eu-central-1.amazonaws.com/coder-base:ubuntu-arm

# Run everything as root
USER root

# Install jupyter
RUN pip3 install jupyterlab==4.0.10

# Set back to coder user
USER coder
